#!/usr/bin/env node
/**
 * ds-push/push.mjs — push changed mp3d/ files to the Magic Patterns design system
 * OVER THE NETWORK, from a script, instead of through model output tokens.
 *
 * WHY THIS EXISTS
 * ---------------
 * `manifest.mjs` removed the *input* cost of a push (local hashing replaced
 * server reads). It could not remove the *output* cost: a file written through
 * an MCP tool call has to be GENERATED by the model, token by token. A 285 KB
 * rules corpus is ~71k output tokens, and output is the slowest thing in the
 * loop — one real rules push burned 555k tokens to ship 63k tokens of content.
 *
 * This script moves the bytes onto the wire. `fs.readFileSync` -> HTTP POST.
 * The model spends tokens deciding WHAT to change and typing one command; the
 * file contents never enter its context in either direction.
 *
 * HOW IT TALKS TO MAGIC PATTERNS
 * ------------------------------
 * There is no documented REST endpoint for design-system FILE writes (v3 REST
 * documents only `GET /api/v3/design-systems`). The write path is the MCP
 * server itself: `https://mcp.magicpatterns.com/mcp` is streamable-HTTP MCP,
 * i.e. JSON-RPC 2.0 over POST with SSE-framed responses, and Magic Patterns
 * documents API-key auth as a first-class alternative to OAuth precisely for
 * "headless environments, CI, or any client where the interactive OAuth flow is
 * impractical". So this file is a ~150-line MCP client that speaks
 * `initialize` -> `notifications/initialized` -> `tools/call`.
 *
 *   docs: /docs/documentation/features/mcp-server/overview#api-key-authentication
 *   docs: /docs/api/getting-started  (same key authenticates REST and MCP)
 *
 * CREDENTIALS
 * -----------
 * The key comes from `MAGICPATTERNS_API_KEY` in the environment and NOWHERE
 * else. It is never written to disk, never printed, and never logged — every
 * diagnostic redacts it. Create one at
 * https://www.magicpatterns.com/settings/api-keys (Settings -> API Keys ->
 * Create Key; it is shown once). API-key auth requires a paid plan.
 *
 * DO NOT commit a key. This repo pushes to a PUBLIC GitHub fork.
 *
 * USAGE
 *   node push.mjs --dry-run            # the plan + exact request shapes, no network, no key needed
 *   node push.mjs                      # push everything `manifest.mjs plan` reports
 *   node push.mjs --paths='rules/*'    # ...restricted to a subset
 *   node push.mjs --verify=content     # hash-verify every write by reading it back (free now!)
 *   node push.mjs --publish            # publish a new DS version after a clean push
 *
 * FLAGS
 *   --dry-run              print the plan and the JSON-RPC request shapes; send nothing
 *   --paths=<glob,glob>    same filter as manifest.mjs
 *   --verify=list|content|none
 *                          list    (default) ONE get_design_system; assert every path is present
 *                          content read every pushed file back and compare sha256 — byte-exact.
 *                                  Costs nothing in model tokens now, so it is cheap to be strict.
 *                          none    trust the write responses only
 *   --publish              call publish_design_system after a fully clean push
 *   --keep-going           do not stop at the first failed call (unsafe: dependency order)
 *   --no-commit            push and verify but leave the manifest dirty
 *   --limit=N              only send the first N write calls
 *   --design-system=ds-... override the target (use for a THROWAWAY test system)
 *   --fat-batches          ignore manifest batching and pack up to --batch-bytes per call
 *   --batch-bytes=N        with --fat-batches, bytes per call (default 1 MB; transport takes >=16 MB)
 *   --json                 machine-readable result summary on stdout
 *   --timeout=MS           per-request timeout (default 120000)
 */

import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  DESIGN_SYSTEM_ID,
  BATCH_MAX_FILES,
  diff,
  makeFilter,
  planBatches,
} from './manifest.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const MCP_URL = process.env.MAGICPATTERNS_MCP_URL || 'https://mcp.magicpatterns.com/mcp';
const AGENT_NAME = 'rct2-ds-push';
const PROTOCOL_VERSION = '2025-06-18';

const argv = process.argv.slice(2);
const has = (f) => argv.includes(f);
const val = (name, dflt) => {
  const a = argv.find((x) => x.startsWith(`--${name}=`));
  return a ? a.slice(name.length + 3) : dflt;
};

const DRY = has('--dry-run');
const JSON_OUT = has('--json');
const VERIFY = val('verify', 'list');
const TIMEOUT = Number(val('timeout', '120000'));
const LIMIT = Number(val('limit', '0'));
const TARGET_DS = val('design-system', DESIGN_SYSTEM_ID);

const kb = (n) => (n / 1024).toFixed(1) + ' KB';
const sha256 = (s) => createHash('sha256').update(s).digest('hex');
// Declarations, not consts: `fail()` is hoisted and may run before this point.
function log(...a) { if (!JSON_OUT) console.log(...a); }
function warn(...a) { console.error(...a); }

if (!['list', 'content', 'none'].includes(VERIFY)) {
  fail(`--verify must be list|content|none (got "${VERIFY}")`);
}

function fail(msg, extra) {
  warn(`\nds-push/push.mjs: ${msg}`);
  if (extra) warn(extra);
  process.exit(1);
}

/**
 * Redact anything that looks like a Magic Patterns key from a string before it
 * can reach a terminal, a log file or a CI transcript.
 */
function redact(s) {
  return String(s).replace(/\bmp_[A-Za-z0-9._-]+/g, 'mp_***REDACTED***');
}

// ---------------------------------------------------------------------------
// Minimal streamable-HTTP MCP client.
//
// Verified against the live server 2026-07: `initialize` negotiates
// protocolVersion 2025-06-18, returns an `mcp-session-id` header that must be
// echoed on every later request, and answers in `text/event-stream` frames.
// `Accept: application/json, text/event-stream` is MANDATORY — omit it and the
// transport refuses the request.
// ---------------------------------------------------------------------------

class McpClient {
  constructor(url, apiKey) {
    this.url = url;
    this.apiKey = apiKey;
    this.sessionId = null;
    this.nextId = 1;
  }

  headers() {
    const h = {
      'content-type': 'application/json',
      accept: 'application/json, text/event-stream',
      // Docs: the MCP server accepts the key as `Authorization: Bearer` OR
      // `x-mp-api-key`. Bearer is the documented form for MCP clients.
      authorization: `Bearer ${this.apiKey}`,
      'x-mp-agent-name': AGENT_NAME,
    };
    if (this.sessionId) h['mcp-session-id'] = this.sessionId;
    return h;
  }

  /** Header shape for --dry-run: same keys, no secret. */
  static exampleHeaders() {
    return {
      'content-type': 'application/json',
      accept: 'application/json, text/event-stream',
      authorization: 'Bearer $MAGICPATTERNS_API_KEY',
      'x-mp-agent-name': AGENT_NAME,
      'mcp-session-id': '<from the initialize response header>',
    };
  }

  async rpc(body, { expectResponse = true } = {}) {
    const ac = new AbortController();
    const t = setTimeout(() => ac.abort(), TIMEOUT);
    let res;
    try {
      res = await fetch(this.url, {
        method: 'POST',
        headers: this.headers(),
        body: JSON.stringify(body),
        signal: ac.signal,
      });
    } catch (e) {
      clearTimeout(t);
      throw new Error(`network error talking to ${this.url}: ${redact(e.message)}`);
    }
    clearTimeout(t);

    const sid = res.headers.get('mcp-session-id');
    if (sid) this.sessionId = sid;

    const text = await res.text();

    if (res.status === 401) {
      throw new AuthError(
        `HTTP 401 from the MCP server. MAGICPATTERNS_API_KEY is missing, malformed, ` +
          `revoked, or the account is not on a paid plan (API-key auth requires one).\n` +
          `  server said: ${redact(text).slice(0, 300)}`
      );
    }
    if (res.status === 402) {
      throw new Error(`HTTP 402 Payment Required — the account is out of Magic Patterns credits.`);
    }
    if (res.status === 413) {
      throw new Error(`HTTP 413 — request body too large. Lower --batch-bytes or drop --fat-batches.`);
    }
    if (res.status === 429) {
      const e = new Error(`HTTP 429 rate limited. Documented limit: 1000 generations / 10 h / key.`);
      e.retryable = true;
      throw e;
    }
    if (!expectResponse) {
      if (res.status >= 400) throw new Error(`HTTP ${res.status}: ${redact(text).slice(0, 300)}`);
      return null;
    }
    if (res.status >= 400) {
      const e = new Error(`HTTP ${res.status} from the MCP transport: ${redact(text).slice(0, 400)}`);
      e.httpStatus = res.status;
      throw e;
    }

    const msg = parseFramed(text, body.id);
    if (!msg) throw new Error(`no JSON-RPC response for id ${body.id} in: ${redact(text).slice(0, 300)}`);
    if (msg.error) {
      const e = new Error(`JSON-RPC error ${msg.error.code}: ${redact(msg.error.message)}`);
      e.rpcCode = msg.error.code;
      throw e;
    }
    return msg.result;
  }

  async connect() {
    const res = await this.rpc({
      jsonrpc: '2.0',
      id: this.nextId++,
      method: 'initialize',
      params: {
        protocolVersion: PROTOCOL_VERSION,
        capabilities: {},
        clientInfo: { name: AGENT_NAME, version: '1.0.0' },
      },
    });
    await this.rpc({ jsonrpc: '2.0', method: 'notifications/initialized' }, { expectResponse: false });
    return res;
  }

  /**
   * Call a tool. NOTE: Magic Patterns reports application-level failures as a
   * HTTP 200 / JSON-RPC *success* carrying `isError: true` and a human string —
   * an invalid key comes back as `Error: Authentication failed. Please log in
   * again.`, not a 401. So `isError` must be checked, not just the status.
   */
  async callTool(name, args) {
    const result = await this.rpc({
      jsonrpc: '2.0',
      id: this.nextId++,
      method: 'tools/call',
      params: { name, arguments: args },
    });
    const text = (result?.content ?? [])
      .filter((c) => c.type === 'text')
      .map((c) => c.text)
      .join('\n');
    let data = result?.structuredContent ?? null;
    if (!data && text) { try { data = JSON.parse(text); } catch { /* prose, not JSON */ } }
    return { isError: !!result?.isError, text, data };
  }

  async close() {
    if (!this.sessionId) return;
    try {
      await fetch(this.url, { method: 'DELETE', headers: this.headers() });
    } catch { /* best effort */ }
  }
}

class AuthError extends Error {}

/** Pull the JSON-RPC message with `id` out of an SSE- or JSON-bodied response. */
function parseFramed(text, id) {
  const candidates = [];
  if (/^\s*[[{]/.test(text)) {
    try { candidates.push(JSON.parse(text)); } catch { /* fall through to SSE */ }
  }
  for (const line of text.split(/\r?\n/)) {
    if (!line.startsWith('data:')) continue;
    const payload = line.slice(5).trim();
    if (!payload || payload === '[DONE]') continue;
    try { candidates.push(JSON.parse(payload)); } catch { /* skip */ }
  }
  const flat = candidates.flatMap((c) => (Array.isArray(c) ? c : [c]));
  return flat.find((m) => m && m.id === id) ?? flat.find((m) => m && (m.result || m.error));
}

// ---------------------------------------------------------------------------
// Failure-mode diagnosis. These are the three we have actually been bitten by.
// ---------------------------------------------------------------------------

function diagnose(callFiles, { text, data, httpStatus }) {
  const t = String(text || '');
  const ve = data?.validationErrors;
  const hasVe = Array.isArray(ve) ? ve.length > 0 : !!ve;
  const names = callFiles.map((f) => f.serverPath).join(', ');
  const out = [];

  if (/Authentication failed|Unauthorized|invalid api key|please log in/i.test(t)) {
    out.push(
      `AUTH FAILED. The server accepted the request but rejected the key.`,
      `  - Is MAGICPATTERNS_API_KEY the full key, including the mp_ prefix?`,
      `  - Keys are shown ONCE; if you lost it, make a new one at`,
      `    https://www.magicpatterns.com/settings/api-keys`,
      `  - API-key auth requires a PAID Magic Patterns plan.`
    );
  }
  if (/\b409\b|conflict|artifact has since changed|has changed since/i.test(t)) {
    out.push(
      `409 CONFLICT — a CONCURRENT SESSION also writes ${TARGET_DS}, and the active`,
      `artifact moved under this write. This script never sends baseArtifactId, so a`,
      `409 means a genuine collision, not drift detection. Nothing was lost: re-run`,
      `push.mjs (the manifest still lists these files as dirty). If it repeats, the`,
      `other session is mid-push — wait for it to finish, then re-run.`
    );
  }
  if ((/\b500\b|internal server error|unexpected server error/i.test(t) || httpStatus === 500) && !hasVe) {
    out.push(
      `HTTP 500 WITH NO validationErrors — this is the UNRESOLVED IMPORT signature.`,
      `One of [${names}] imports something that is not on the server yet.`,
      `DO NOT edit the file to work around it. Push the dependency FIRST, then re-send`,
      `this file unchanged. Dependency order is package.json/tailwind.config.js/index.css`,
      `-> leaf .ts -> .tsx submodules -> index.tsx -> *.previews.tsx -> Context.md -> rules/*.md.`,
      `If the dependency is a NEW component, its whole trio has to land in one push.`
    );
  }
  if (hasVe) {
    const list = Array.isArray(ve) ? ve : [ve];
    out.push(`validationErrors (${list.length}) — NON-BLOCKING for the write, FATAL for publish:`);
    for (const v of list.slice(0, 20)) out.push(`  - ${redact(typeof v === 'string' ? v : JSON.stringify(v))}`);
    if (/previews|Context\.md|index\.tsx|trio|default export/i.test(JSON.stringify(list))) {
      out.push(
        `INCOMPLETE COMPONENT TRIO. Every code component needs all three of`,
        `  components/<Name>/index.tsx        (NAMED export — a default export rejects the write)`,
        `  components/<Name>/<Name>.previews.tsx  (DEFAULT-exported previews object)`,
        `  components/<Name>/Context.md`,
        `write_design_system_files tolerates a partial trio; publish_design_system does`,
        `NOT — it refuses while any validationError stands. Complete the trio, re-push,`,
        `then publish.`
      );
    }
  }
  if (/credit|402/i.test(t)) out.push(`Out of credits — top up at https://www.magicpatterns.com/settings/subscription`);
  if (!out.length) out.push(`Unrecognised failure. Raw server text:\n  ${redact(t).slice(0, 800)}`);
  return out;
}

// ---------------------------------------------------------------------------
// Planning
// ---------------------------------------------------------------------------

function fatBatches(changed, maxBytes) {
  const calls = [];
  let cur = null;
  for (const f of changed) {
    if (!cur || cur.bytes + f.bytes > maxBytes) {
      if (cur) calls.push(cur);
      cur = { kind: 'batch', files: [], bytes: 0 };
    }
    cur.files.push(f);
    cur.bytes += f.bytes;
  }
  if (cur?.files.length) calls.push(cur);
  return calls.map((c) => (c.files.length === 1 ? { ...c, kind: 'single' } : c));
}

function buildPlan() {
  const { changed, local, unchanged, orphans } = diff({ filter: makeFilter(argv) });
  let calls = has('--fat-batches')
    ? fatBatches(changed, Number(val('batch-bytes', String(1024 * 1024))))
    : planBatches(changed);
  if (LIMIT > 0) calls = calls.slice(0, LIMIT);
  return { changed, local, unchanged, orphans, calls };
}

/** The `arguments` object for one write call — file bytes read straight off disk. */
function writeArgs(call) {
  return {
    designSystemId: TARGET_DS,
    // baseArtifactId is DELIBERATELY OMITTED — a concurrent session also pushes
    // to this design system and sending a base id turns each of its writes into
    // a 409 for us. Writes merge onto the active artifact, so omitting it is
    // safe for disjoint file sets.
    files: call.files.map((f) => ({
      fileName: f.serverPath,
      content: fs.readFileSync(f.abs, 'utf8'),
    })),
  };
}

// ---------------------------------------------------------------------------
// --dry-run
// ---------------------------------------------------------------------------

function dryRun(plan) {
  const { changed, local, unchanged, calls } = plan;
  const total = changed.reduce((s, f) => s + f.bytes, 0);
  const planned = calls.flatMap((c) => c.files).reduce((s, f) => s + f.bytes, 0);

  log(`DRY RUN — nothing will be sent. No API key required.\n`);
  log(`endpoint       : POST ${MCP_URL}   (streamable-HTTP MCP, JSON-RPC 2.0)`);
  log(`design system  : ${TARGET_DS}${TARGET_DS === DESIGN_SYSTEM_ID ? '' : '   (OVERRIDDEN)'}`);
  log(`credential     : $MAGICPATTERNS_API_KEY  ->  Authorization: Bearer <key>`);
  log(`                 ${process.env.MAGICPATTERNS_API_KEY ? 'SET in this environment' : 'NOT SET (fine for --dry-run; required to push)'}`);
  log(`local push set : ${local.length} files   unchanged: ${unchanged.length}   TO PUSH: ${changed.length}`);
  log(`bytes on wire  : ${kb(planned)}${planned !== total ? ` of ${kb(total)} changed (--limit)` : ''}`);
  log(`model tokens for those bytes: 0  (the old cost was ~${Math.round(planned / 4)} output tokens)`);
  log(`verification   : ${VERIFY}${VERIFY === 'content' ? '  (reads every file back and compares sha256)' : ''}`);
  log(`publish after  : ${has('--publish') ? 'YES (publish_design_system)' : 'no'}`);
  log(`commit after   : ${has('--no-commit') ? 'no (--no-commit)' : 'YES (manifest.mjs commit <verified paths>)'}`);

  log(`\nHANDSHAKE — 2 requests before any write:\n`);
  log(`  1. POST ${MCP_URL}`);
  log(`     headers ${JSON.stringify(McpClient.exampleHeaders(), null, 2).replace(/\n/g, '\n     ')}`);
  log(`     body    ${JSON.stringify({ jsonrpc: '2.0', id: 1, method: 'initialize', params: { protocolVersion: PROTOCOL_VERSION, capabilities: {}, clientInfo: { name: AGENT_NAME, version: '1.0.0' } } })}`);
  log(`     -> 200 text/event-stream, header  mcp-session-id: <uuid>   (echo it on every later request)`);
  log(`  2. POST ${MCP_URL}`);
  log(`     body    ${JSON.stringify({ jsonrpc: '2.0', method: 'notifications/initialized' })}   -> 202, no body`);

  if (!calls.length) {
    log(`\nNothing to push.`);
    return;
  }

  log(`\nWRITE CALLS — ${calls.length} tools/call request(s), in dependency order:\n`);
  let id = 2;
  for (const [i, c] of calls.entries()) {
    id++;
    log(
      `  ${String(i + 1).padStart(3)}. ${c.kind === 'single' ? 'SINGLE' : 'BATCH '}  ${kb(c.bytes).padStart(9)}  ${c.files.length} file(s)`
    );
    for (const f of c.files) {
      log(`        ${String(f.bytes).padStart(7)} B  sha256:${f.sha256.slice(0, 12)}  ${f.serverPath}`);
    }
    // Show the real body with content elided — the shape, not the payload.
    const body = {
      jsonrpc: '2.0',
      id,
      method: 'tools/call',
      params: {
        name: 'write_design_system_files',
        arguments: {
          designSystemId: TARGET_DS,
          files: c.files.map((f) => ({
            fileName: f.serverPath,
            content: `<${f.bytes} bytes read from ${path.relative(HERE, f.abs)}>`,
          })),
        },
      },
    };
    log(`        body: ${JSON.stringify(body)}`);
  }

  log(`\nAFTER THE WRITES:`);
  if (VERIFY === 'list')
    log(`  tools/call get_design_system {"designSystemId":"${TARGET_DS}"}  -> assert all ${calls.flatMap((c) => c.files).length} path(s) in result.files`);
  if (VERIFY === 'content') {
    log(`  tools/call get_design_system {"designSystemId":"${TARGET_DS}"}  -> path presence`);
    log(`  tools/call read_design_system_files {"designSystemId":"${TARGET_DS}","fileNames":[…]} in chunks of ${BATCH_MAX_FILES}`);
    log(`      -> sha256 each returned content against the local hash. Byte-exact, and free now.`);
  }
  if (has('--publish')) log(`  tools/call publish_design_system {"designSystemId":"${TARGET_DS}"}`);
  if (!has('--no-commit'))
    log(`  node manifest.mjs commit <every verified path>   (only verified paths — a path that`);
  if (!has('--no-commit')) log(`      did not verify stays dirty so the next run retries it)`);
  log(`  DELETE ${MCP_URL}  (mcp-session-id: <uuid>) to release the session`);

  log(`\nRe-run without --dry-run to send it. Requires:  export MAGICPATTERNS_API_KEY=mp_...`);
}

// ---------------------------------------------------------------------------
// live push
// ---------------------------------------------------------------------------

async function livePush(plan) {
  const apiKey = process.env.MAGICPATTERNS_API_KEY;
  if (!apiKey) {
    fail(
      `MAGICPATTERNS_API_KEY is not set — refusing to push.`,
      `
  This script authenticates ONLY from the environment. To enable it:

    1. Sign in at https://www.magicpatterns.com/  (API-key auth needs a PAID plan)
    2. Open  Settings -> API Keys   ( https://www.magicpatterns.com/settings/api-keys )
    3. Click "Create Key" and copy it IMMEDIATELY — it is shown exactly once
    4. Export it in the shell that runs this script:

         export MAGICPATTERNS_API_KEY='mp_...'

  NEVER put the key in a file in this repo, a shell script, or a commit — this
  repo pushes to a PUBLIC GitHub fork. Prefer a keychain/1Password shell hook,
  or an untracked ~/.config file you source by hand.

  You can preview everything this script would do without a key:

    node push.mjs --dry-run`
    );
  }
  if (!/^mp_/.test(apiKey)) {
    warn(
      `warning: MAGICPATTERNS_API_KEY does not start with "mp_" — Magic Patterns keys do.\n` +
        `         Continuing anyway; a bad key surfaces as an auth error below.`
    );
  }

  const { calls } = plan;
  if (!calls.length && !has('--publish')) {
    log(`Nothing to push.`);
    return { pushed: [], failed: [], verified: [] };
  }
  // NOTHING DIRTY *AND* `--publish`: publish anyway. A push and its publish are
  // two separate server calls, so the natural two-step — push, eyeball the
  // verification, then publish — used to be impossible: by the time you ran the
  // second command the manifest was clean and this early return swallowed the
  // `--publish` silently, reporting "Nothing to push" as if it had done what you
  // asked. Re-running with `--publish` now cuts straight to the publish call.
  if (!calls.length) {
    log(`nothing to push — running --publish only (the working set is already on the server).`);
    const only = new McpClient(MCP_URL, apiKey);
    try {
      log(`connecting to ${MCP_URL} …`);
      await only.connect();
      log(`\npublishing …`);
      const p = await only.callTool('publish_design_system', { designSystemId: TARGET_DS });
      if (p.isError) {
        warn(`  publish REJECTED: ${redact(p.text)}`);
        return { pushed: [], failed: [], verified: [], published: false };
      }
      const v = p.data?.version;
      log(`  published${v ? ` v${v.major}.${v.minor}` : ''}${p.data?.isBackwardsCompatible === false ? '  (BREAKING)' : ''}`);
      return { pushed: [], failed: [], verified: [], published: true };
    } finally {
      await only.close?.();
    }
  }

  const client = new McpClient(MCP_URL, apiKey);
  const t0 = Date.now();
  log(`connecting to ${MCP_URL} …`);
  let server;
  try {
    server = await client.connect();
  } catch (e) {
    if (e instanceof AuthError) fail(e.message);
    fail(`handshake failed: ${redact(e.message)}`);
  }
  log(`connected: ${server?.serverInfo?.name} ${server?.serverInfo?.version} (protocol ${server?.protocolVersion})`);
  log(`target    : ${TARGET_DS}`);

  const pushed = [];
  const failed = [];
  let sentBytes = 0;
  let stop = false;

  for (const [i, c] of calls.entries()) {
    if (stop) {
      failed.push(...c.files.map((f) => ({ file: f, why: 'skipped after an earlier failure' })));
      continue;
    }
    const label = `[${i + 1}/${calls.length}] ${c.kind === 'single' ? 'SINGLE' : 'BATCH '} ${kb(c.bytes).padStart(9)}  ${c.files.map((f) => f.serverPath).join(', ')}`;
    const started = Date.now();
    sentBytes += c.bytes;
    let res;
    try {
      res = await client.callTool('write_design_system_files', writeArgs(c));
    } catch (e) {
      if (e instanceof AuthError) { await client.close(); fail(e.message); }
      warn(`${label}\n  FAILED: ${redact(e.message)}`);
      for (const line of diagnose(c.files, { text: e.message, httpStatus: e.httpStatus })) warn(`  ${line}`);
      failed.push(...c.files.map((f) => ({ file: f, why: e.message })));
      if (!has('--keep-going')) stop = true;
      continue;
    }
    const ms = Date.now() - started;

    if (res.isError) {
      warn(`${label}\n  REJECTED after ${ms} ms`);
      for (const line of diagnose(c.files, res)) warn(`  ${line}`);
      failed.push(...c.files.map((f) => ({ file: f, why: res.text })));
      if (!has('--keep-going')) stop = true;
      continue;
    }

    const ve = res.data?.validationErrors;
    const veList = Array.isArray(ve) ? ve : ve ? [ve] : [];
    log(`${label}\n  ok in ${ms} ms (${Math.round(c.bytes / 1024 / (ms / 1000))} KB/s)${veList.length ? `  — ${veList.length} validationError(s)` : ''}`);
    if (veList.length) for (const line of diagnose(c.files, res)) warn(`  ${line}`);
    pushed.push(...c.files);
  }

  // ---- verification -------------------------------------------------------
  let verified = pushed;
  if (VERIFY !== 'none' && pushed.length) {
    log(`\nverifying (${VERIFY}) …`);
    const ds = await client.callTool('get_design_system', { designSystemId: TARGET_DS });
    if (ds.isError) {
      warn(`  get_design_system failed: ${redact(ds.text)} — refusing to commit anything.`);
      verified = [];
    } else {
      const names = new Set(
        (ds.data?.files ?? []).map((f) => (typeof f === 'string' ? f : f.name ?? f.fileName))
      );
      const missing = pushed.filter((f) => !names.has(f.serverPath));
      for (const f of missing) warn(`  MISSING on the server: ${f.serverPath} — staying dirty`);
      verified = pushed.filter((f) => names.has(f.serverPath));
      log(`  path list: ${verified.length}/${pushed.length} present (server holds ${names.size} files)`);

      if (VERIFY === 'content' && verified.length) {
        const good = [];
        for (let i = 0; i < verified.length; i += BATCH_MAX_FILES) {
          const chunk = verified.slice(i, i + BATCH_MAX_FILES);
          const r = await client.callTool('read_design_system_files', {
            designSystemId: TARGET_DS,
            fileNames: chunk.map((f) => f.serverPath),
          });
          if (r.isError) {
            warn(`  read-back failed for ${chunk.map((f) => f.serverPath).join(', ')}: ${redact(r.text)}`);
            continue;
          }
          const byName = new Map((r.data?.files ?? []).map((f) => [f.name ?? f.fileName, f.content]));
          for (const f of chunk) {
            const content = byName.get(f.serverPath);
            if (content == null) { warn(`  read-back returned nothing for ${f.serverPath}`); continue; }
            const remote = sha256(Buffer.from(content, 'utf8'));
            if (remote === f.sha256) good.push(f);
            else
              warn(
                `  SHA MISMATCH ${f.serverPath}: local ${f.sha256.slice(0, 12)} (${f.bytes} B) vs server ${remote.slice(0, 12)} (${Buffer.byteLength(content)} B) — staying dirty`
              );
          }
        }
        log(`  content: ${good.length}/${verified.length} byte-identical`);
        verified = good;
      }
    }
  }

  // ---- publish ------------------------------------------------------------
  if (has('--publish')) {
    if (failed.length) {
      warn(`\nskipping --publish: ${failed.length} file(s) failed. publish_design_system is STRICT.`);
    } else {
      log(`\npublishing …`);
      const p = await client.callTool('publish_design_system', { designSystemId: TARGET_DS });
      if (p.isError) {
        warn(`  publish REJECTED: ${redact(p.text)}`);
        for (const line of diagnose(pushed, p)) warn(`  ${line}`);
      } else {
        const v = p.data?.version;
        log(`  published${v ? ` v${v.major}.${v.minor}` : ''}${p.data?.isBackwardsCompatible === false ? '  (BREAKING)' : ''}`);
      }
    }
  }

  await client.close();

  // ---- commit -------------------------------------------------------------
  if (verified.length && !has('--no-commit')) {
    log(`\nrecording ${verified.length} verified file(s) in the manifest …`);
    try {
      const out = execFileSync(
        process.execPath,
        [path.join(HERE, 'manifest.mjs'), 'commit', ...verified.map((f) => f.serverPath)],
        { encoding: 'utf8' }
      );
      log(out.trim().split('\n').slice(0, 3).join('\n') + (verified.length > 2 ? `\n  … ${verified.length} paths` : ''));
    } catch (e) {
      warn(`manifest commit FAILED: ${redact(e.stdout || e.message)}`);
      warn(`Files ARE on the server; the manifest just did not record them. Re-run:`);
      warn(`  node manifest.mjs commit ${verified.map((f) => f.serverPath).join(' ')}`);
    }
  } else if (verified.length) {
    log(`\n--no-commit: manifest left dirty for ${verified.length} verified file(s).`);
  }

  const secs = ((Date.now() - t0) / 1000).toFixed(1);
  const bytes = verified.reduce((s, f) => s + f.bytes, 0);
  log(
    `\ndone in ${secs}s — ${verified.length} verified, ${failed.length} failed, ` +
      `${kb(sentBytes)} sent / ${kb(bytes)} landed, 0 output tokens of file content.`
  );
  return { pushed, failed, verified, seconds: Number(secs), bytes, sentBytes };
}

// ---------------------------------------------------------------------------

if (has('--help') || has('-h')) {
  console.log(fs.readFileSync(fileURLToPath(import.meta.url), 'utf8').split('*/')[0]);
  process.exit(0);
}

const plan = buildPlan();
if (DRY) {
  dryRun(plan);
  if (JSON_OUT)
    console.log(
      JSON.stringify(
        {
          dryRun: true,
          endpoint: MCP_URL,
          designSystemId: TARGET_DS,
          apiKeyPresent: !!process.env.MAGICPATTERNS_API_KEY,
          verify: VERIFY,
          calls: plan.calls.map((c) => ({
            kind: c.kind,
            bytes: c.bytes,
            files: c.files.map((f) => ({ fileName: f.serverPath, bytes: f.bytes, sha256: f.sha256 })),
          })),
          totalBytes: plan.calls.flatMap((c) => c.files).reduce((s, f) => s + f.bytes, 0),
        },
        null,
        2
      )
    );
} else {
  const r = await livePush(plan);
  if (JSON_OUT)
    console.log(
      JSON.stringify(
        {
          designSystemId: TARGET_DS,
          verified: r.verified.map((f) => f.serverPath),
          failed: r.failed.map((f) => ({ fileName: f.file.serverPath, why: redact(f.why).slice(0, 200) })),
          bytes: r.bytes ?? 0,
          seconds: r.seconds ?? 0,
        },
        null,
        2
      )
    );
  if (r.failed.length) process.exit(1);
}
